language: node_js

node_js:
    - "10"

dist: trusty

sudo: required

branches:
    only:
        - master

before_script:
    - npm install -g @angular/cli

script:
    - ng tslint
    - ng stylelint
    - ng build --prod --base-href https://ofcyln.github.io/currency-exchange/
